<?php

namespace Framework\Discovery;

use Framework\Contracts\Cacheable;
use Framework\Contracts\Discoverable;
use Framework\Supports\Facades\File;
use ReflectionClass;
use ReflectionMethod;
use ReflectionNamedType;

use function Framework\app;
use function Framework\app_path;
use function Framework\collection;
use function Framework\config_path;

class ListenerDiscovery implements Discoverable, Cacheable
{
    /**
     * The discovered listeners array .
     *
     * @var array
     */
    protected $listeners = [];

    /**
     * Discover the listeners from the file system.
     *
     * @return self
     */
    public function discover()
    {
        // For the production mode we will cache the listeners to improve the performance.
        // So don't need to discover the listeners from the filesystem.
        if (!app()->is_dev_mode()) {
            return $this;
        }

        $listeners_directory = app_path('Listeners');

        if (!file_exists($listeners_directory)) {
            return $this;
        }

        $listeners_files = glob($listeners_directory . '/*.php');

        if (empty($listeners_files)) {
            return $this;
        }

        foreach ($listeners_files as $file) {
            $listener = $this->listener_class(
                $this->filename($file)
            );

            if (!$this->is_valid_listener($listener)) {
                continue;
            }

            $event = $this->event_class($listener);

            if (is_null($event)) {
                continue;
            }

            $priority = $this->priority($listener);

            $this->listeners[$event][] = compact(
                'listener',
                'priority'
            );
        }

        return $this;
    }

    /**
     * Get the listeners array.
     *
     * @return array
     */
    public function listeners()
    {
        return $this->prepare($this->listeners);
    }

    /**
     * Get the priority of the listener.
     *
     * @param string $listener
     * @return int
     */
    protected function priority(string $listener)
    {
        $reflection = new ReflectionClass($listener);
        $method = $reflection->getMethod('priority');

        return $method->invoke(
            $reflection->newInstanceWithoutConstructor()
        );
    }

    /**
     * Get the event class of the listener.
     *
     * @param string $listener
     * @return string|null
     */
    protected function event_class(string $listener)
    {
        $method = new ReflectionMethod($listener, 'handle');
        $parameters = $method->getParameters();

        if (empty($parameters) || count($parameters) !== 1) {
            return null;
        }

        $parameter = $parameters[0];
        $type = $parameter->getType();
        $type_name = $type instanceof ReflectionNamedType ? $type->getName() : (string) $type;

        if (!class_exists($type_name)) {
            return null;
        }

        return $type_name;
    }

    /**
     * Get the filename of the listener.
     *
     * @param string $file
     * @return string
     */
    protected function filename(string $file)
    {
        return basename($file, '.php');
    }

    /**
     * Get the listener class of the filename.
     *
     * @param string $filename
     * @return string
     */
    protected function listener_class(string $filename)
    {
        $app_namespace = rtrim(app()->get_namespace(), '\\');
        $namespace = $app_namespace . '\\Listeners\\';

        return $namespace . $filename;
    }

    /**
     * Check if the listener is valid.
     *
     * @param string $listener
     * @return bool
     */
    protected function is_valid_listener(string $listener)
    {
        if (!class_exists($listener)) {
            return false;
        }

        $reflection = new ReflectionClass($listener);

        if (!$reflection->hasMethod('handle')) {
            return false;
        }

        return true;
    }

    /**
     * Cache the listeners.
     *
     * @param string|null $path
     * @return $this
     */
    public function cache($path = null)
    {
        $path = $path ?? config_path('listeners.cache.php');

        if (!$this->is_cacheable($path)) {
            return $this;
        }

        File::put(
            $path,
            "<?php \r\n\r\n/** Auto generated by discovering the listeners. Don't edit this file manually. */\r\n\r\nreturn " . var_export($this->listeners(), true) . ';'
        );

        return $this;
    }

    /**
     * Check if the listeners are cacheable.
     *
     * @param string $path
     * @return bool
     */
    public function is_cacheable(string $path)
    {
        return app()->is_dev_mode() || File::missing($path);
    }

    /**
     * Prioritize the listeners.
     *
     * @param array $listeners
     * @return array
     */
    protected function prioritize(array $listeners)
    {
        usort($listeners, function ($first, $second) {
            return $second['priority'] - $first['priority'];
        });

        return $listeners;
    }

    /**
     * Prepare the listeners.
     *
     * @param array $listeners
     * @return array
     */
    protected function prepare(array $listeners)
    {
        $prepared = [];

        foreach ($listeners as $event => $listener) {
            $prepared[$event] = collection($this->prioritize($listener))
                ->pluck('listener')
                ->all();
        }

        return $prepared;
    }
}
